### ISSUE TITLE
Cannot run cz 2.20.1

### ISSUE THREAD

**Issue by dtrodrigues** [commitizen-tools/commitizen#458]
## Description
cz 2.20.1 has a runtime dependency of `typing-extensions` but it isn't declared as a dependency in `pyproject.toml`

## Steps to reproduce
1. Run `pip install commitizen==2.20.1`
2. Run `cz`

## Current behavior
```
# cz version
Traceback (most recent call last):
  File "/usr/local/bin/cz", line 5, in <module>
    from commitizen.cli import main
  File "/usr/local/lib/python3.9/site-packages/commitizen/__init__.py", line 6, in <module>
    from commitizen.cz.base import BaseCommitizen
  File "/usr/local/lib/python3.9/site-packages/commitizen/cz/__init__.py", line 5, in <module>
    from commitizen.cz.base import BaseCommitizen
  File "/usr/local/lib/python3.9/site-packages/commitizen/cz/base.py", line 7, in <module>
    from commitizen.config.base_config import BaseConfig
  File "/usr/local/lib/python3.9/site-packages/commitizen/config/__init__.py", line 4, in <module>
    from commitizen import defaults, git
  File "/usr/local/lib/python3.9/site-packages/commitizen/defaults.py", line 5, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

## Desired behavior
```
# cz version
2.20.1
```

## Environment

Add output of the following command to include the following
- commitizen version: 2.20.1
- python version: 3.9
- operating system: any (Fedora 34, macOS 11)
```bash
cz version --report
```

**Comment by Lee-W** [comment]
hi thanks for reporting, I just notice that and create a PR for that.

**Comment by dtrodrigues** [comment]
Fixed in newest release.

**Comment by Ancientshield** [comment]
I use [https://formulae.brew.sh/formula/commitizen](https://formulae.brew.sh/formula/commitizen), but can't not use.

Intel macOS Ventura 13.1

```
cz version --report
Traceback (most recent call last):
  File "/usr/local/bin/cz", line 5, in <module>
    from commitizen.cli import main
  File "/usr/local/Cellar/commitizen/2.39.1/libexec/lib/python3.11/site-packages/commitizen/__init__.py", line 2, in <module>
    import logging.config
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/config.py", line 30, in <module>
    import logging.handlers
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 26, in <module>
    import io, logging, socket, os, pickle, struct, time, re
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 550, in <module>
    import array
ImportError: dlopen(/usr/local/lib/python3.11/lib-dynload/array.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__PyFloat_Unpack4'
```

**Comment by Lee-W** [comment]
Hi @Ancientshield Thanks for reporting! Could you please create it as a standalone issue so that we could track it? Thanks!
