### ISSUE TITLE
NotImplementedError with prompt-toolkit version 3.0.25

### ISSUE THREAD

**Issue by u-iandono** [commitizen-tools/commitizen#478]
## Description
One of commitizen's dependencies, `prompt-toolkit`, was updated to version 3.0.25 after executing `pipenv update`. After that, I constantly receive this problem when I execute `cz c`.

```sh
  File "C:\Python39\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
```
Only happens with `cz c` command.

To resolve the issue, I must explicitly include `prompt-toolkit` version 3.0.24 as my dependency.

## Steps to reproduce
1. Run `pipenv update`
2. Check that prompt-toolkit is version 3.0.25.
3. Run `cz c`

## Current behavior
I got this error:

```sh
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\Scripts\cz.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\commitizen\cli.py", line 317, in main
    args.func(conf, vars(args))()
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\commitizen\commands\commit.py", line 74, in __call__
    m = self.prompt_commit_questions()
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\commitizen\commands\commit.py", line 52, in prompt_commit_question
s
    answers = questionary.prompt(questions, style=cz.style)
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\questionary\prompt.py", line 68, in prompt
    return unsafe_prompt(questions, answers, patch_stdout, true_color, **kwargs)
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\questionary\prompt.py", line 194, in unsafe_prompt
    answer = question.unsafe_ask(patch_stdout)
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\questionary\question.py", line 92, in unsafe_ask
    return self.application.run()
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\prompt_toolkit\application\application.py", line 930, in run      
    return loop.run_until_complete(
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\prompt_toolkit\application\application.py", line 849, in run_async
    return await _run_async2()
  File "C:\Users\x\.virtualenvs\y-M0aUaMTg\lib\site-packages\prompt_toolkit\application\application.py", line 801, in _run_asyn
    loop.add_signal_handler(
  File "C:\Python39\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
```

## Desired behavior
It should show the normal prompt.

**Screenshots**

## Environment

Add output of the following command to include the following
- Commitizen Version: 2.20.4
- Python Version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
- Operating System: Windows
```bash
cz version --report
```

**Comment by Lee-W** [comment]
Looks like an error due to https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1553. Could you please update `prompt-toolkit` to 3.0.26 and try again? Thanks!

**Comment by u-iandono** [comment]
@Lee-W I just checked, its back to normal now!

Thank you!
