### ISSUE TITLE
I use https://formulae.brew.sh/formula/commitizen, but can't not use.  Intel macOS Ventura 13.1

### ISSUE THREAD

**Issue by Ancientshield** [commitizen-tools/commitizen#652]
### Description

I use [https://formulae.brew.sh/formula/commitizen](https://formulae.brew.sh/formula/commitizen), but can't not run.

### Steps to reproduce

brew install commitizen
cz version --report

### Current behavior

```
cz version --report
Traceback (most recent call last):
  File "/usr/local/bin/cz", line 5, in <module>
    from commitizen.cli import main
  File "/usr/local/Cellar/commitizen/2.39.1/libexec/lib/python3.11/site-packages/commitizen/__init__.py", line 2, in <module>
    import logging.config
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/config.py", line 30, in <module>
    import logging.handlers
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 26, in <module>
    import io, logging, socket, os, pickle, struct, time, re
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 550, in <module>
    import array
ImportError: dlopen(/usr/local/lib/python3.11/lib-dynload/array.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__PyFloat_Unpack4'
```

### Desired behavior

Intel macOS Ventura 13.1

### Environment

Intel macOS Ventura 13.1

**Comment by woile** [comment]
Closing for now, please feel free to reopen if it happens again
